In [3]:
# Import Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB


In [4]:
#  Load All CSV Files


sellers = pd.read_csv("/Users/arul/Documents/VASUKI/projects/Brazllian E-commerce public dataset/archive/olist_sellers_dataset.csv")
products = pd.read_csv("/Users/arul/Documents/VASUKI/projects/Brazllian E-commerce public dataset/archive/olist_products_dataset.csv")
product_translation = pd.read_csv("/Users/arul/Documents/VASUKI/projects/Brazllian E-commerce public dataset/archive/product_category_name_translation.csv")
reviews = pd.read_csv("/Users/arul/Documents/VASUKI/projects/Brazllian E-commerce public dataset/archive/olist_order_reviews_dataset.csv")
orders = pd.read_csv("/Users/arul/Documents/VASUKI/projects/Brazllian E-commerce public dataset/archive/olist_orders_dataset.csv")
payments = pd.read_csv("/Users/arul/Documents/VASUKI/projects/Brazllian E-commerce public dataset/archive/olist_order_payments_dataset.csv")
order_items = pd.read_csv("/Users/arul/Documents/VASUKI/projects/Brazllian E-commerce public dataset/archive/olist_order_items_dataset.csv")
geolocation = pd.read_csv("/Users/arul/Documents/VASUKI/projects/Brazllian E-commerce public dataset/archive/olist_geolocation_dataset.csv")
customers = pd.read_csv("/Users/arul/Documents/VASUKI/projects/Brazllian E-commerce public dataset/archive/olist_customers_dataset.csv")


In [6]:
# Quick Peek at Each Dataset

# sellers

print(sellers.shape)
print(sellers.columns)
sellers.head()

(3095, 4)
Index(['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state'], dtype='object')


seller_id  seller_zip_code_prefix  \
0  3442f8959a84dea7ee197c632cb2df15                   13023   
1  d1b65fc7debc3361ea86b5f14c68d2e2                   13844   
2  ce3ad9de960102d0677a81f5d0bb7b2d                   20031   
3  c0f3eea2e14555b6faeea3dd58c1b1c3                    4195   
4  51a04a8a6bdcb23deccc82b0b80742cf                   12914   

         seller_city seller_state  
0           campinas           SP  
1         mogi guacu           SP  
2     rio de janeiro           RJ  
3          sao paulo           SP  
4  braganca paulista           SP

In [7]:
# products

print(products.shape)
print(products.columns)
products.head()

(32951, 9)
Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='object')


product_id  product_category_name  \
0  1e9e8ef04dbcff4541ed26657ea517e5             perfumaria   
1  3aa071139cb16b67ca9e5dea641aaa2f                  artes   
2  96bd76ec8810374ed1b65e291975717f          esporte_lazer   
3  cef67bcfe19066a932b7673e239eb23d                  bebes   
4  9dc1a7de274444849c219cff195d0b71  utilidades_domesticas   

   product_name_lenght  product_description_lenght  product_photos_qty  \
0                 40.0                       287.0                 1.0   
1                 44.0                       276.0                 1.0   
2                 46.0                       250.0                 1.0   
3                 27.0                       261.0                 1.0   
4                 37.0                       402.0                 4.0   

   product_weight_g  product_length_cm  product_height_cm  product_width_cm  
0             225.0               16.0               10.0              14.0  
1            1000.0               30.0               18.0              20.0  
2             154.0               18.0                9.0              15.0  
3             371.0               26.0                4.0              26.0  
4             625.0               20.0               17.0              13.0

In [8]:
# product_translation

print(product_translation.shape)
print(product_translation.columns)
product_translation.head()

(71, 2)
Index(['product_category_name', 'product_category_name_english'], dtype='object')


product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [9]:
# reviews

print(reviews.shape)
print(reviews.columns)
reviews.head()

(99224, 7)
Index(['review_id', 'order_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='object')


review_id                          order_id  \
0  7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb   
1  80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33   
2  228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b   
3  e64fb393e7b32834bb789ff8bb30750e  658677c97b385a9be170737859d3511b   
4  f7c4243c7fe1938f181bec41a392bdeb  8e6bfb81e283fa7e4f11123a3fb894f1   

   review_score review_comment_title  \
0             4                  NaN   
1             5                  NaN   
2             5                  NaN   
3             5                  NaN   
4             5                  NaN   

                              review_comment_message review_creation_date  \
0                                                NaN  2018-01-18 00:00:00   
1                                                NaN  2018-03-10 00:00:00   
2                                                NaN  2018-02-17 00:00:00   
3              Recebi bem antes do prazo estipulado.  2017-04-21 00:00:00   
4  Parabéns lojas lannister adorei comprar pela I...  2018-03-01 00:00:00   

  review_answer_timestamp  
0     2018-01-18 21:46:59  
1     2018-03-11 03:05:13  
2     2018-02-18 14:36:24  
3     2017-04-21 22:02:06  
4     2018-03-02 10:26:53

In [10]:
# orders

print(orders.shape)
print(orders.columns)
orders.head()

(99441, 8)
Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='object')


order_id                       customer_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d   
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef   
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089   
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82   
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c   

  order_status order_purchase_timestamp    order_approved_at  \
0    delivered      2017-10-02 10:56:33  2017-10-02 11:07:15   
1    delivered      2018-07-24 20:41:37  2018-07-26 03:24:27   
2    delivered      2018-08-08 08:38:49  2018-08-08 08:55:23   
3    delivered      2017-11-18 19:28:06  2017-11-18 19:45:59   
4    delivered      2018-02-13 21:18:39  2018-02-13 22:20:29   

  order_delivered_carrier_date order_delivered_customer_date  \
0          2017-10-04 19:55:00           2017-10-10 21:25:13   
1          2018-07-26 14:31:00           2018-08-07 15:27:45   
2          2018-08-08 13:50:00           2018-08-17 18:06:29   
3          2017-11-22 13:39:59           2017-12-02 00:28:42   
4          2018-02-14 19:46:34           2018-02-16 18:17:02   

  order_estimated_delivery_date  
0           2017-10-18 00:00:00  
1           2018-08-13 00:00:00  
2           2018-09-04 00:00:00  
3           2017-12-15 00:00:00  
4           2018-02-26 00:00:00

The history saving thread hit an unexpected error (OperationalError('unable to open database file')).History will not be written to the database.


In [11]:
# payments

print(payments.shape)
print(payments.columns)
payments.head()

(103886, 5)
Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='object')


order_id  payment_sequential payment_type  \
0  b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card   
1  a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card   
2  25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card   
3  ba78997921bbcdc1373bb41e913ab953                   1  credit_card   
4  42fdf880ba16b47b59251dd489d4441a                   1  credit_card   

   payment_installments  payment_value  
0                     8          99.33  
1                     1          24.39  
2                     1          65.71  
3                     8         107.78  
4                     2         128.45

In [12]:
# order_items

print(order_items.shape)
print(order_items.columns)
order_items.head()

(112650, 7)
Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='object')


order_id  order_item_id  \
0  00010242fe8c5a6d1ba2dd792cb16214              1   
1  00018f77f2f0320c557190d7a144bdd3              1   
2  000229ec398224ef6ca0657da4fc703e              1   
3  00024acbcdf0a6daa1e931b038114c75              1   
4  00042b26cf59d7ce69dfabb4e55b4fd9              1   

                         product_id                         seller_id  \
0  4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202   
1  e5f2d52b802189ee658865ca93d83a8f  dd7ddc04e1b6c2c614352b383efe2d36   
2  c777355d18b72b67abbeef9df44fd0fd  5b51032eddd242adc84c38acab88f23d   
3  7634da152a4610f1595efa32f14722fc  9d7a1d34a5052409006425275ba1c2b4   
4  ac6c3623068f30de03045865e4e10089  df560393f3a51e74553ab94004ba5c87   

   shipping_limit_date   price  freight_value  
0  2017-09-19 09:45:35   58.90          13.29  
1  2017-05-03 11:05:13  239.90          19.93  
2  2018-01-18 14:48:30  199.00          17.87  
3  2018-08-15 10:10:18   12.99          12.79  
4  2017-02-13 13:57:51  199.90          18.14

In [13]:
# geolocation

print(geolocation.shape)
print(geolocation.columns)
geolocation.head()

(1000163, 5)
Index(['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng',
       'geolocation_city', 'geolocation_state'],
      dtype='object')


geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
0                         1037       -23.545621       -46.639292   
1                         1046       -23.546081       -46.644820   
2                         1046       -23.546129       -46.642951   
3                         1041       -23.544392       -46.639499   
4                         1035       -23.541578       -46.641607   

  geolocation_city geolocation_state  
0        sao paulo                SP  
1        sao paulo                SP  
2        sao paulo                SP  
3        sao paulo                SP  
4        sao paulo                SP

In [14]:
# customers

print(customers.shape)
print(customers.columns)
customers.head()

(99441, 5)
Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='object')


customer_id                customer_unique_id  \
0  06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0   
1  18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3   
2  4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e   
3  b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c   
4  4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066   

   customer_zip_code_prefix          customer_city customer_state  
0                     14409                 franca             SP  
1                      9790  sao bernardo do campo             SP  
2                      1151              sao paulo             SP  
3                      8775        mogi das cruzes             SP  
4                     13056               campinas             SP

In [15]:
#  Check for Missing Values

# sellers

sellers.isnull().sum()


seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [16]:
# products

products.isnull().sum()


product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [17]:
# product_translation

product_translation.isnull().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [18]:
# reviews

reviews.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [19]:
# orders

orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [20]:
#payments

payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [21]:
# order_items

order_items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [22]:
# geolocation

geolocation.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [23]:
# customers

customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [24]:
# Handling the project file

# Drop rows with 610 missing values
products.dropna(subset=['product_category_name', 
                        'product_name_lenght', 
                        'product_description_lenght', 
                        'product_photos_qty'], inplace=True)

# Fill numerical dimensions with median
for col in ['product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']:
    products[col].fillna(products[col].median(), inplace=True)


In [25]:
# products

products.isnull().sum()


product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

In [26]:
# handling the review file

reviews['review_comment_title'].fillna('', inplace=True)
reviews['review_comment_message'].fillna('', inplace=True)


In [27]:
# reviews

reviews.isnull().sum()

review_id                  0
order_id                   0
review_score               0
review_comment_title       0
review_comment_message     0
review_creation_date       0
review_answer_timestamp    0
dtype: int64

In [34]:
# handling order file

# Keep only delivered orders
orders = orders[orders['order_delivered_customer_date'].notnull()]


In [33]:
# orders

orders.isnull().sum()

order_id                         0
customer_id                      0
order_status                     0
order_purchase_timestamp         0
order_approved_at                0
order_delivered_carrier_date     1
order_delivered_customer_date    0
order_estimated_delivery_date    0
is_delivered                     0
delivery_time_days               0
dtype: int64

In [36]:
# Merging Datasets

# STEP 1: Start with orders (already cleaned)
df = orders.copy()

# STEP 2: Merge with order items
df = df.merge(order_items, on='order_id', how='left')

# STEP 3: Merge with products
df = df.merge(products, on='product_id', how='left')

# STEP 4: Merge with product category translation
df = df.merge(product_translation, on='product_category_name', how='left')

# STEP 5: Merge with sellers
df = df.merge(sellers, on='seller_id', how='left')

# STEP 6: Merge with customers
df = df.merge(customers, on='customer_id', how='left')

# STEP 7: Merge with payments
df = df.merge(payments, on='order_id', how='left')

# STEP 8: Merge with reviews
df = df.merge(reviews, on='order_id', how='left')


In [37]:
# Feature Engineering

# Order & Delivery Features

# Convert to datetime
df['order_purchase_timestamp'] = pd.to_datetime(df['order_purchase_timestamp'])
df['order_delivered_customer_date'] = pd.to_datetime(df['order_delivered_customer_date'])
df['order_estimated_delivery_date'] = pd.to_datetime(df['order_estimated_delivery_date'])

# Actual delivery time (in days)
df['delivery_time'] = (df['order_delivered_customer_date'] - df['order_purchase_timestamp']).dt.days

# Delivery delay (positive = late, negative = early)
df['delay_vs_estimated'] = (df['order_delivered_customer_date'] - df['order_estimated_delivery_date']).dt.days


In [38]:
#  Review Features

# Review text length
df['review_len'] = df['review_comment_message'].apply(lambda x: len(str(x)))

# Review sentiment (optional, simple version)
def simple_sentiment(score):
    if score >= 4:
        return 'positive'
    elif score == 3:
        return 'neutral'
    else:
        return 'negative'

df['review_sentiment'] = df['review_score'].apply(simple_sentiment)


In [39]:
# Payment Features

# If multiple payments per order: keep as-is or group by order
# Already merged, so get total payment value if needed

df['payment_value'] = df['payment_value'].fillna(0)


In [40]:
# Product Features

# Product name length and description length
df['product_name_lenght'] = df['product_name_lenght'].fillna(0)
df['product_description_lenght'] = df['product_description_lenght'].fillna(0)

# Price per item
df['price_per_item'] = df['price'] / df['order_item_id']


In [ ]:
# Review Score Prediction

In [41]:
# Preprocessing

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Select features
features = ['delivery_time', 'delay_vs_estimated', 'price', 'freight_value', 'review_len', 'payment_value']
X = df[features]
y = df['review_score']

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [43]:
# Drop rows where review_score is NaN before model training.

# Drop rows where review_score is missing
df = df[df['review_score'].notnull()]


In [44]:
# Features and target
features = ['delivery_time', 'delay_vs_estimated', 'price', 'freight_value', 'review_len', 'payment_value']
X = df[features]
y = df['review_score']


In [45]:
# check if any of your feature columns have NaN:

print(X.isnull().sum())


delivery_time         0
delay_vs_estimated    0
price                 0
freight_value         0
review_len            0
payment_value         0
dtype: int64


In [47]:
# Modeling


# 1. Define your feature columns
features = ['delivery_time', 'delay_vs_estimated', 'price', 'freight_value', 'review_len', 'payment_value']

# 2. Subset your DataFrame with both features and target
model_df = df[features + ['review_score']]

# 3. Drop all rows where either X or y is missing
model_df = model_df.dropna()

# 4. Split into features and target
X = model_df[features]
y = model_df['review_score']

# 5. Now train/test split and model
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 6. Fit model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# 7. Predict and evaluate
y_pred = model.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


[[ 1729    13    38    71   801]
 [  175   215    14    30   398]
 [  187    11   445   105  1188]
 [  152    11    50  1045  3213]
 [  287    20   121   637 12017]]
              precision    recall  f1-score   support

         1.0       0.68      0.65      0.67      2652
         2.0       0.80      0.26      0.39       832
         3.0       0.67      0.23      0.34      1936
         4.0       0.55      0.23      0.33      4471
         5.0       0.68      0.92      0.78     13082

    accuracy                           0.67     22973
   macro avg       0.68      0.46      0.50     22973
weighted avg       0.66      0.67      0.63     22973



In [48]:
# Interpretation (for Tableau or storytelling)

import pandas as pd
importance = pd.DataFrame({'feature': features, 'importance': model.feature_importances_})
importance.sort_values(by='importance', ascending=False, inplace=True)


In [49]:
# Review Sentiment Analysis with NLP

# Dataset: review_comment_message and review_score

# Start with relevant columns
nlp_df = df[['review_comment_message', 'review_score']].copy()

# Drop missing reviews
nlp_df.dropna(subset=['review_comment_message'], inplace=True)


In [50]:
# Create Sentiment Labels

# Convert review_score into sentiment label
def map_sentiment(score):
    if score <= 2:
        return 'negative'
    elif score == 3:
        return 'neutral'
    else:
        return 'positive'

nlp_df['sentiment'] = nlp_df['review_score'].apply(map_sentiment)


In [51]:
# Text Cleaning (Basic)

import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^\w\s]', '', text)  # Remove punctuation
    text = re.sub(r'\d+', '', text)      # Remove numbers
    return text

nlp_df['cleaned_text'] = nlp_df['review_comment_message'].apply(clean_text)


In [52]:
# Feature Extraction: TF-IDF

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=3000)
X = vectorizer.fit_transform(nlp_df['cleaned_text'])
y = nlp_df['sentiment']


In [53]:
# Train NLP Classification Model

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, confusion_matrix

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = MultinomialNB()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


[[ 1993    65  1426]
 [  341    94  1501]
 [  225    64 17264]]
              precision    recall  f1-score   support

    negative       0.78      0.57      0.66      3484
     neutral       0.42      0.05      0.09      1936
    positive       0.86      0.98      0.91     17553

    accuracy                           0.84     22973
   macro avg       0.69      0.53      0.55     22973
weighted avg       0.81      0.84      0.81     22973



In [54]:
#  Export for Tableau 

nlp_df['predicted_sentiment'] = model.predict(X)

# Save to CSV
nlp_df[['review_comment_message', 'sentiment', 'predicted_sentiment']].to_csv("review_sentiment_results.csv", index=False)


In [55]:
# Generate Word Cloud Data for Each Sentiment

# Prepare Data

# Only keep cleaned text and sentiment
text_data = nlp_df[['cleaned_text', 'sentiment']].copy()


In [56]:
# Compute Word Frequencies per Sentiment

from collections import Counter
import pandas as pd

# Create dictionary to hold word counts
sentiment_word_freq = {}

# Loop through each sentiment category
for sentiment in ['positive', 'neutral', 'negative']:
    # Get all cleaned texts for this sentiment
    texts = text_data[text_data['sentiment'] == sentiment]['cleaned_text']
    
    # Split all texts into words and flatten
    all_words = ' '.join(texts).split()
    
    # Count frequency
    word_counts = Counter(all_words)
    
    # Convert to DataFrame
    freq_df = pd.DataFrame(word_counts.items(), columns=['word', 'frequency'])
    freq_df['sentiment'] = sentiment
    
    # Save to dict
    sentiment_word_freq[sentiment] = freq_df


In [58]:
# Save All Frequencies to One CSV

# Combine all DataFrames into one
final_word_freq_df = pd.concat(sentiment_word_freq.values(), ignore_index=True)

# Save to CSV
final_word_freq_df.to_csv("word_frequencies_by_sentiment.csv", index=False)
